# Generated by Django 5.2 on 2025-05-08 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='destination_warehouse_id',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='origin_warehouse_id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.JSONField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.JSONField(),
            preserve_default=False,
        ),
    ]
