# Generated by Django 5.2 on 2025-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_fuelrecord_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='depot_id',
            field=models.CharField(blank=True, help_text='External ID of the depot this vehicle is assigned to', max_length=64, null=True),
        ),
    ]
