# Generated by Django 5.2 on 2025-05-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicle_depot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='depot_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='depot_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
